apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailhog-pvc
  namespace: mailhog
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi

